apiVersion: skaffold/v1
kind: Config
# Enforce SKaffold to use Jib
build:

  artifacts:
    - image: roynilanjan1/bootifull-skaffold
      # Use jibGradle
      jib: {}
  tagPolicy:
    gitCommit: {}
# Execute deployment.yml
deploy:
    kubectl:
       manifests:
       - kubernetes/*.yaml